version: "3"
services:
  app:
    image: san-jose-turnos
    build:
      context: .
      secrets:
        - env
    ports:
      - "5173:5173"
    env_file:
      - .env
secrets:
  env:
    file: .env