[build]
  publish = "dist" # Cambia esto según tu carpeta de salida, como build o public
  command = "npm run build" # Comando para construir la aplicación

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200